# Generated by Django 4.2.6 on 2023-10-07 20:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="category",
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="sections",
            field=models.JSONField(default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="service",
            name="title",
            field=models.CharField(default="a", max_length=250),
            preserve_default=False,
        ),
    ]
