# Generated by Django 4.2.6 on 2023-10-07 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("services", "0002_service_category_service_sections_service_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="sections",
            field=models.JSONField(default=list),
        ),
    ]
