# Generated by Django 4.2.6 on 2023-10-07 18:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user_profile", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(default=1, max_length=13),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="userprofile",
            name="picture",
            field=models.ImageField(default=1, upload_to="profile_pictures/"),
            preserve_default=False,
        ),
    ]
