"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 4.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path

from datetime import timedelta

from .utils import get_variable_from_env

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = get_variable_from_env("SECRET_KEY")

DEBUG = get_variable_from_env("DEBUG", boolean=True)

ALLOWED_HOSTS = get_variable_from_env("ALLOWED_HOSTS", iterable=True)


# Application definition

DJANGO_BUILT_IN_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

THIRD_PARTY_APPS = [
    "corsheaders",  # pip install django-cors-headers
    "rest_framework",  # pip install djangorestframework
    "rest_framework_simplejwt",  # pip install djangorestframework-simplejwt,
]

PROJECT_APPS = [
    "apps.base_app",
    "apps.user_profile",
    "apps.demands",
    "apps.services",
]

INSTALLED_APPS = DJANGO_BUILT_IN_APPS + THIRD_PARTY_APPS + PROJECT_APPS

INSTALLED_APPS += [
    "debug_toolbar",
]

INTERNAL_IPS = [
    # https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#configure-internal-ips
    # ...
    "127.0.0.1",
    # ...
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    # https://pypi.org/project/django-cors-headers/
    "corsheaders.middleware.CorsMiddleware",  # doc manda botar antes de CommonMiddleware # TODO: Ver maneira de fazer isso dinamicamente, igual fiz no debug toolbar
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

MIDDLEWARE = [
    # https://django-debug-toolbar.readthedocs.io/en/latest/installation.html#add-the-middleware
    "debug_toolbar.middleware.DebugToolbarMiddleware",
] + MIDDLEWARE


ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     "default": {
#         "ENGINE": "django.db.backends.sqlite3",
#         "NAME": BASE_DIR / "db.sqlite3",
#     }
# }

DATABASES = {
    "default": {
        "ENGINE": get_variable_from_env("DATABASE_ENGINE"),
        "NAME": get_variable_from_env("DATABASE_NAME"),
        "USER": get_variable_from_env("DATABASE_USER"),
        "PASSWORD": get_variable_from_env("DATABASE_PASSWORD"),
        "HOST": get_variable_from_env("DATABASE_HOST"),
        "PORT": get_variable_from_env("DATABASE_PORT"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Rest Framework Configuration
# Docs: https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
}

CORS_ALLOW_ALL_ORIGINS = True  # Use only in development

# Rest Framework SimpleJWT Configuration
# Docs: https://django-rest-framework-simplejwt.readthedocs.io/

# if DEBUG:
#     SIMPLE_JWT = {
#         'ACCESS_TOKEN_LIFETIME': timedelta(weeks=200),
#     }

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(weeks=200),
}


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "/static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# The URL's or named URL patterns where requests are redirected after login or logout
# https://docs.djangoproject.com/en/3.2/ref/settings/#std-setting-LOGIN_REDIRECT_URL

LOGIN_URL = "login"

LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "login"
