# Generated by Django 4.2.6 on 2023-10-07 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Demand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("text", models.TextField()),
                ("code", models.CharField(blank=True, editable=False, max_length=10)),
                (
                    "status",
                    models.IntegerField(
                        choices=[
                            (0, "Aberto"),
                            (1, "Em Andamento"),
                            (2, "Concluido"),
                            (3, "Recusado"),
                        ],
                        default=0,
                    ),
                ),
                ("rejection_reason", models.TextField(blank=True, null=True)),
                ("picture", models.ImageField(upload_to="demand_pictures/")),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
