# Generated by Django 4.2.6 on 2023-10-08 00:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="demand_pictures/"
            ),
        ),
    ]
