# Generated by Django 4.2.6 on 2023-10-07 09:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="code",
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
