# Generated by Django 4.2.6 on 2023-10-08 03:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demands", "0002_alter_demand_picture"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="supports",
            field=models.ManyToManyField(
                related_name="supported_demands", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
