# Generated by Django 4.2.6 on 2023-10-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0002_alter_demand_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="code",
            field=models.CharField(
                blank=True, editable=False, max_length=10, unique=True
            ),
        ),
    ]
