# Generated by Django 4.2.6 on 2023-10-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0004_alter_demand_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="status",
            field=models.IntegerField(
                choices=[
                    (0, "Aberto"),
                    (1, "Em Andamento"),
                    (2, "Concluido"),
                    (3, "Recusado"),
                ],
                default=0,
            ),
        ),
    ]
