# Generated by Django 4.2.6 on 2023-10-08 10:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demands", "0004_remove_demand_supports_support"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="support",
            unique_together={("user", "demand")},
        ),
    ]
