# Generated by Django 4.2.6 on 2023-10-07 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("demands", "0005_demand_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="demand",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
