# Generated by Django 4.2.6 on 2023-10-08 12:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("demands", "0005_alter_support_unique_together"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demand",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="demands",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
